on:
  push:
    branches: [main, auto, canary]
  pull_request:
    branches:
      - main

name: Test coverage

jobs:
  coverage:
    name: Collect test coverage
    runs-on: "ubuntu-latest"
    env:
      RUSTFLAGS: -D warnings
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: llvm-tools-preview
      - uses: Swatinem/rust-cache@v2

      - name: Install latest nextest release
        uses: taiki-e/install-action@v2
        with:
          tool: nextest
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov

      - name: Collect coverage data
        run: |
          cargo llvm-cov nextest