on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main

name: Tests

jobs:
  coverage:
    name: Collect test coverage
    runs-on: "ubuntu-latest"
    env:
      RUSTFLAGS: -D warnings
      CARGO_TERM_COLOR: always
    steps:
      - name: Set warnings as errors for drafts
        if: github.event_name == 'pull_request' && github.event.pull_request.draft == false
        run: echo "RUSTFLAGS=-D warnings" >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
      - name: Cache rust and cargo
        uses: swatinem/rust-cache@v2
      - name: Install nextest and cargo-llvm-cov
        uses: taiki-e/install-action@v2
        with:
          tool: nextest,cargo-llvm-cov
      - name: Collect coverage data
        run: |
          cargo llvm-cov nextest